CREATE TABLE COCHES
(
    MATRICULA       VARCHAR(7),
    MARCA           VARCHAR(25),
    MODELO          VARCHAR(30),
    ANNO            INTEGER,

    CONSTRAINT "PK_COCHES"        PRIMARY KEY (MATRICULA),
    CONSTRAINT "NN_COCHES.MARCA" CHECK ( MARCA IS NOT NULL ),
    CONSTRAINT "NN_COCHES.MODELO" CHECK ( MODELO IS NOT NULL ),
    CONSTRAINT "NN_COCHES.ANNO" CHECK ( ANNO  IS NOT NULL )
);

CREATE SEQUENCE SEQ_COCHES MINVALUE 1 MAXVALUE 999998 START WITH 1 INCREMENT BY 1;

INSERT INTO COCHES(MATRICULA, MARCA, MODELO, ANNO) VALUES('1234AAA', 'Mercedes', 'Clase C', 2007);
INSERT INTO COCHES(MATRICULA, MARCA, MODELO, ANNO) VALUES('3434BBB', 'Toyota', 'Land Cruiser', 2012);
INSERT INTO COCHES(MATRICULA, MARCA, MODELO, ANNO) VALUES('5555CCC', 'Lexus', 'IS-300h', 2020);
INSERT INTO COCHES(MATRICULA, MARCA, MODELO, ANNO) VALUES('7777DDD', 'Seat', 'Ibiza', 2003);
INSERT INTO COCHES(MATRICULA, MARCA, MODELO, ANNO) VALUES('8888EEE', 'Porsche', 'Panamera', 2018);

COMMIT;