#Este fichero lo creamos nosotros, despues de payara/micro: hacemos control+space y la mas reciente?
# Intel
FROM payara/micro:6.2023.12-jdk17
    #Lo sacamos de la carpeta target al hacer mvn install
COPY target/backend-1.0.0.war                         /opt/payara/deployments/ROOT.war
